[package]
name = "gitsail-cli"
version = "0.0.0"
edition.workspace = true

[dependencies]
gitsail-application = { path = "../gitsail-application" }
gitsail-domain = { path = "../gitsail-domain" }
gitsail-git = { path = "../gitsail-git" }
gitsail-protocol = { path = "../gitsail-protocol" }

[lints]
workspace = true
